### ISSUE TITLE
Linking cases to portions of text

### ISSUE THREAD

**Issue by casillamo** [Ronggui/RQDA#28]
Thanks for your work. I am trying to create cases from within one source (different cases in the same source) but the cases are not saved, and the highlighting disappears as soon as I try to link another portion of text to a different case. I am running RQDA in Windows 10.

**Comment by twigdip** [comment]
This was a bug which has now been fixed by Ronggui Huang:
https://github.com/Ronggui/RQDA

**Comment by pablogrod** [comment]
El 11/3/19 a las 09:07, twigdip escribió:
>
> This was a bug which has now been fixed by Ronggui Huang:
> https://github.com/Ronggui/RQDA
>
I do not see it is fixed. I uninstalled RQDA, updated all installed 
packages in RStudio, reinstalled RQDA with the command

> /install.packages("RQDA",dependencies=c("Depends", "Imports"))/

suggested in the page http://rqda.r-forge.r-project.org/.

The version of RQDA is the same. And the problem still persist. Presing 
the "Link" button do not add the selected fragment of text to the 
selected case. :-(

How can we access the fixed version?


-- 

	
*Dr. Pablo Gustavo Rodriguez
*Email: * pablogrod@disroot.org <mailto:pablogrod@disroot.org>
*Perfil *Academia.edu <http://unlp.academia.edu/PabloGustavoRodriguez>
*Perfil *ResearchGate 
<https://www.researchgate.net/profile/Pablo_Rodriguez18/?ev=hdr_xprf>
<http://pablogrodriguez.blogspot.com/>*Blog personal: 
<http://pablogrodriguez.blogspot.com.ar/>*
*Universidad Nacional de La Plata**

**Comment by twigdip** [comment]
#if you didn’t install remotes already then do it now
install.packages("remotes")
library(remotes)
install_github("Ronggui/RQDA")

**Comment by twigdip** [comment]
It doesn't work if you simply reinstall RQDA because the main file hasn't been updated (you have to install through Github)

**Comment by pablogrod** [comment]
Thanks a lot for your response!. I already run the suggested commands and I still do not see the issue fixed. Is there anything else I should do? When you say that I have to install RQDA through Github, does it mean I should download the RQDA-master.zip? And unzip it within the RQDA folder? or the folder containing the RQDA folder? In my system it is located in /home/pablogr/R/x86_64-pc-linux-gnu-library/3.2/RQDA 
I guess it is the developer version. Is this one what you mean? 
Should I follow the instructions in the section "Installation of Devel Version"?
Excuse me but I am just a user, not a developer, and some things are not obvious to me.

**Comment by twigdip** [comment]
Hi there - I'm sorry but I'm not an expert on using R either! Are you using RStudio? I had no problems installing this from GitHub - but I did have to try a few times...

install.packages("remotes")
library(remotes)
install_github("Ronggui/RQDA")

Are you getting any errors? Try installing a few times if it doesn't work? And try reinstalling RQDA after you've run it through GitHub....

**Comment by pablogrod** [comment]
I had a message error on igraph compilation

> make: *** [igraph.so] Error 1
> ERROR: compilation failed for package ‘igraph’
> * removing ‘/home/pablogr/R/x86_64-pc-linux-gnu-library/3.2/igraph’

I will try reinstalling several times as twigdip suggests

**Comment by n8craig** [comment]
I am having the same issue. When trying to add a file to a case, the console shows:

> Error: Columns `data` not found

... the file is not added to the case. To resolve this issue I tried the install method suggested above:

`install.packages("remotes")`
`library(remotes)`
`install_github("Ronggui/RQDA")`

I also tried the install method from the GitHub [Readme.md](https://github.com/Ronggui/RQDA) instructions for Win:

`install.packages("devtools") ## install it only if you haven't done it yet`
`require(devtools)`
`devtools::install_github("Ronggui/RQDA")`

Additionally, I tried downloading and running the portable version. The two methods of install fail with quite a few error messages key being that:

1. RGtk2 is not installed (I installed it following those [instructions](https://gist.github.com/sebkopf/9405675))
2. the PATH environment variable is not set (which I set to `R/win-library/3.6/RGtk2/`). 

The other error, which I suspect is related perhaps to the path issue, is:
> unable to load shared object 'C:/.../R/win-library/3.6/RGtk2/libs/i386/RGtk2.dll' LoadLibrary failure: Specified module could not be found.

Any help sorting this out so that I can use the cases function, would be very much appreciated.

**Comment by twigdip** [comment]
Hi there,I'm sorry but I don't think I'll be able to help. I was in touch with Ronggui directly and he helpfully replied that he was going to update the actual official version eventually but it doesn't seem that he has. I ended up using a copy of Atlas.ti as it was getting so frustrating with RQDA, but it's a great bit package for R...shame it isn't getting developed much.The only thing I can suggest you do is try an older or different version of RQDA. I think I managed to make my cases work in the end with an older version...but I can't remember exactly now as it was a while ago and I haven't been using RQDA since.All the best though 
    On Wednesday, 29 April 2020, 03:05:04 BST, n8craig <notifications@github.com> wrote:  
 
 


I am having the same issue. When trying to add a file to a case, the console shows:


Error: Columns data not found


... the file is not added to the case. To resolve this issue I tried the install method suggested above:

install.packages("remotes")
library(remotes)
install_github("Ronggui/RQDA")

I also tried the install method from the GitHub Readme.md instructions for Win:

install.packages("devtools") ## install it only if you haven't done it yet
require(devtools)
devtools::install_github("Ronggui/RQDA")

Additionally, I tried downloading and running the portable version. The two methods of install fail with quite a few error messages key being that:
   
   - RGtk2 is not installed (I installed it following those instructions)
   - the PATH environment variable is not set (which I set to R/win-library/3.6/RGtk2/).

The other error, which I suspect is related perhaps to the path issue, is:


unable to load shared object 'C:/.../R/win-library/3.6/RGtk2/libs/i386/RGtk2.dll' LoadLibrary failure: Specified module could not be found.


Any help sorting this out so that I can use the cases function, would be very much appreciated.
